module.exports = {
    FETCH_TOKEN_STARTED: "FETCH_TOKEN_STARTED",
    FETCH_TOKEN_COMPLETED: "FETCH_TOKEN_COMPLETED",
    RECEIVE_TOKEN_WUNDERLIST: "RECEIVE_TOKEN_WUNDERLIST",
    RECEIVE_USER_DATA: "RECEIVE_USER_DATA",
    NO_WUNDERLIST_TOKEN: "NO_WUNDERLIST_TOKEN"
};
