/**
 * Created by robby on 2/22/16.
 */

module.exports = {
    SET_INITIAL_STATE: "SET_INITIAL_STATE",
    PERFORM_NEXT_STEP: "PERFORM_NEXT_STEP",
    PERFORM_NEXT_STEP_COMPLETE: "PERFORM_NEXT_STEP_COMPLETE",
    FLOW_STATE_SIGN_UP: "FLOW_STATE_SIGN_UP",
    FLOW_STATE_LOG_IN: "FLOW_STATE_LOG_IN",
    FLOW_STATE_QUIZ_LAUNCH: "FLOW_STATE_QUIZ_LAUNCH",
    FLOW_STATE_PAYMENT_INFO: "FLOW_STATE_PAYMENT_INFO"
    FLOW_STATE_ACCOUNT_CONNECT: "FLOW_STATE_ACCOUNT_CONNECT"
};
