/**
 * Created by robby on 2/12/16.
 */

module.exports = {
    SET_CREATOR_FORM_TYPE: "SET_CREATOR_FORM_TYPE",
    SCRAPE_LINK_STARTED: "SCRAPE_LINK_STARTED",
    SCRAPE_LINK_FINISHED: "SCRAPE_LINK_FINISHED",
    RECEIVE_PREVIEW_CONTENT: "RECEIVE_PREVIEW_CONTENT",
    MODE_CREATE: "MODE_CREATE",
    MODE_EDIT: "MODE_EDIT"
};