module.exports = {
    "RECEIVE_TYPEFORM_RESPONSE_DATA": "RECEIVE_TYPEFORM_RESPONSE_DATA",

    "QUIZ_ID_ONBOARDING": "EPf23h",
    "QUIZ_ID_MEGA_QUIZ": "EL7VfM",
    "QUIZ_ID_UPLOAD": "YXSviA",
    "QUIZ_ID_ENTER_MORE_TASKS": "sMxukk",
    "QUIZ_ID_PROFILE": "PPt4il",
    "QUIZ_ID_PROFILE_CONTROL": "PPt4il",
    "QUIZ_ID_PROFILE_RUNNING": "gWR1pk",
    "QUIZ_ID_PROFILE_PRODUCTIVITY": "PGIqo7",
    "QUIZ_ID_ONBOARDING_CONTROL": "XvnVwA",
    "QUIZ_ID_ONBOARDING_PRODUCTIVITY": "cDBkJO",
    "QUIZ_ID_ONBOARDING_RUNNING": "Ba4KKi",
};
