module.exports = {
    TASK_CREATE_ALL: "TASK_CREATE_ALL",
    TASK_CREATE: "TASK_CREATE",
    TASK_UPDATE: "TASK_UPDATE",
    TASK_ARCHIVE: "TASK_ARCHIVE",
    TASK_DESTROY: "TASK_DESTROY",
    TASK_COMPLETE: "TASK_COMPLETE",
    TASK_UNDO_COMPLETE: "TASK_UNDO_COMPLETE",
    TASK_CLEAR: "TASK_CLEAR"
};
