/**
 * Created by liztron on 1/27/16.
 */
module.exports = {
    RECEIVE_USER_DATA: "RECEIVE_USER_DATA",
    SET_USER_NAME: "SET_USER_NAME",
    SET_USER_BIRTHDAY: "SET_USER_BIRTHDAY",
    SET_USER_EMAIL: "SET_USER_EMAIL",
    SET_USER_PHONE: "SET_USER_PHONE",
    SET_USER_GENDER: "SET_USER_GENDER",
    SET_USER_LOCATION_NAME: "SET_USER_LOCATION_NAME",
    SET_USER_TIMEZONE: "SET_USER_TIMEZONE"
};