module.exports = {
    RECEIVE_STREAM: "RECEIVE_STREAM",
    RECEIVE_FEATURED_STREAM_OBJECT: "RECEIVE_FEATURED_STREAM_OBJECT",
    SELECT_STREAM_OBJECT: "SELECT_STREAM_OBJECT",
    UPDATE_STREAM_OBJECT: "UPDATE_STREAM_OBJECT",
    CREATE_STREAM_OBJECT: "CREATE_STREAM_OBJECT",
    PREVIEW_STREAM_OBJECT: "PREVIEW_STREAM_OBJECT",
    DELETE_STREAM_OBJECT: "DELETE_STREAM_OBJECT",
    CLEAR_STREAM_OBJECT_SELECTION: "CLEAR_STREAM_OBJECT_SELECTION",
    SET_TIP_RATING: "SET_TIP_RATING",
    SET_TIP_COMMENT: "SET_TIP_COMMENT",
    LOADING_STARTED: "STREAM_LOADING_STARTED",
    LOADING_FINISHED: "STREAM_LOADING_FINISHED"
};
