module.exports = {
    "RECEIVE_LIST_TASKS":"RECEIVE_LIST_TASKS",
    "RECEIVE_LIST_WITH_TASKS":"RECEIVE_LIST_WITH_TASKS",
    "RECEIVE_LIST_COMPLETED_TASKS":"RECEIVE_LIST_COMPLETED_TASKS",
    "RECEIVE_LIST_DATA": "RECEIVE_LIST_DATA",
    "ALL_TASKS_FETCHED": "ALL_TASKS_FETCHED",
    "TASKS_FETCH_STARTED": "TASKS_FETCH_STARTED"
};
