module.exports = {
  "RECEIVE_LIST_TASKS": "RECEIVE_LIST_TASKS",
  "RECEIVE_LIST_COMPLETED_TASKS": "RECEIVE_LIST_COMPLETED_TASKS",
  "RECEIVE_LIST_DATA": "RECEIVE_LIST_DATA",
  "RECEIVE_TYPEFORM_RESPONSE_DATA": "RECEIVE_TYPEFORM_RESPONSE_DATA",
  "RECEIVE_USER_DATA": "RECEIVE_USER_DATA",
  "ALL_TASKS_FETCHED": "ALL_TASKS_FETCHED",
  "TASKS_FETCH_STARTED": "TASKS_FETCH_STARTED",
  "RECEIVE_ADMIN_USER_NOTES": "RECEIVE_ADMIN_USER_NOTES",
  "GET_ADMIN_USER_NOTES": "GET_ADMIN_USER_NOTES",
  "UPDATE_ADMIN_USER_NOTES": "UPDATE_ADMIN_USER_NOTES"
};